sudo: false
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - GIT_NAME: TravisCI
    - GIT_EMAIL: tonjayin+robot@gmail.com
    - GITHUB_REPO: ztbcms/docs
    - GIT_SOURCE: _book  
before_install:
  - npm install -g gitbook-cli@2.3.0
  - npm install 
  - gitbook install
script:
  - make generate
after_success:
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi
